name: Update README

on:
  schedule:
    - cron: '*/5 * * * *' # Update every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@{2.3.4}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
